table Dim_Airports
	lineageTag: bacfe722-21c5-40be-8adb-bb89b28f003e

	column Airport_Code
		dataType: string
		lineageTag: 6772907f-f5f8-47d0-908e-5b150c443ff2
		summarizeBy: none
		sourceColumn: Airport_Code

		annotation SummarizationSetBy = Automatic

	column Airport_Name
		dataType: string
		lineageTag: 1ca5e237-4287-4a58-b43a-41ceb92163e4
		summarizeBy: none
		sourceColumn: Airport_Name

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e5509a7c-32ae-4af8-bc3e-91a4a48ef0bd
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 43b37b6a-4298-4201-a9c3-303a54bb3119
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 8ad47748-7454-445d-b0a4-722342acd358
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 79fca683-38b2-4cf5-88c9-3ba19ac574d1
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hub_Type
		dataType: string
		lineageTag: 9aba68ca-b17f-4106-8df2-72fdef1a18a3
		summarizeBy: none
		sourceColumn: Hub_Type

		annotation SummarizationSetBy = Automatic

	partition Dim_Airports = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\danak\Desktop\Airline_Analytics_Project\Dim_Airports.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Airport_Code", type text}, {"Airport_Name", type text}, {"City", type text}, {"Country", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Hub_Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

